name: Test for Development
'on':
  push:
    branches:
      - dev
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing the dependencies
        run: npm i
      - name: Unit testing
        run: npm test
